[tool.poetry]
name = "slide-generator"
version = "0.1.0"
description = ""
authors = ["haruto2001 <tarako5515@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.2.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
